blank_issues_enabled: false
contact_links:
  - name: Report Chocolatey Package Issue
    url: https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process
    about: Reporting issues with a Chocolatey package?
  - name: Ask Questions on forum
    url: https://groups.google.com/forum/#!forum/chocolatey
    about: Do you have a question?
  - name: Ask Questions in public chat
    url: https://ch0.co/community
    about: Do you have questions?